### ISSUE TITLE
Bad url for 1st page

### ISSUE THREAD

**Issue by morilval** [getgrav/grav-plugin-pagination#15] opened 2016-03-10 20:58 UTC
```
<div class="post-nav archive-nav pagination">
            <a rel="prev" href="">«</a>
                            <a href="">1</a>
                                <a href="#" class="current">2</a>
                                <a href="/page:3">3</a>
                                <a href="/page:4">4</a>
                        <a rel="next" href="/page:3">»</a>
    </div>
```

**Comment by flaviocopes** [comment] 2016-03-11 08:54
Cannot replicate:

```
<ul class="pagination">
  <li><a rel="prev" href="/grav/it/blog/page:4">&laquo;</a></li>
  <li><a href="/grav/it/blog">1</a></li>
  <li><a href="/grav/it/blog/page:2">2</a></li>
  <li><a href="/grav/it/blog/page:3">3</a></li>
  <li><a href="/grav/it/blog/page:4">4</a></li>
  <li><span>5</span></li>
  <li><a href="/grav/it/blog/page:6">6</a></li>
  <li><a href="/grav/it/blog/page:7">7</a></li>
  <li><a href="/grav/it/blog/page:8">8</a></li>
  <li><a href="/grav/it/blog/page:9">9</a></li>
  <li><a href="/grav/it/blog/page:10">10</a></li>
  <li><a href="/grav/it/blog/page:11">11</a></li>
  <li><a rel="next" href="/grav/it/blog/page:6">&raquo;</a></li>
</ul>
```

Using Antimatter.

Which theme are you using?

**Comment by flaviocopes** [comment] 2016-03-11 08:55
Seeing your output seems the default `pagination.html.twig` from the plugin https://github.com/getgrav/grav-plugin-pagination/blob/develop/templates/partials/pagination.html.twig is overwritten in the theme, might want to compare the two.

**Comment by rhukster** [comment] 2016-03-11 15:03
pagination should work with no subdomain at the root of a site.  I did fix/test this a couple of times.  Perhaps the logic is not updated in either pagination or antimatter.. will need to investigate.

**Comment by flaviocopes** [comment] 2016-03-11 17:24
Same with root blog

```
<ul class="pagination">
  <li><a rel="prev" href="/page:3">&laquo;</a></li>
  <li><a href="/">1</a></li>
  <li><a href="/page:2">2</a></li>
  <li><a href="/page:3">3</a></li>
  <li><span>4</span></li>
  <li><a href="/page:5">5</a></li>
  <li><a href="/page:6">6</a></li>
  <li><a href="/page:7">7</a></li>
  <li><a href="/page:8">8</a></li>
  <li><a href="/page:9">9</a></li>
  <li><a href="/page:10">10</a></li>
  <li><a href="/page:11">11</a></li>
  <li><a rel="next" href="/page:5">&raquo;</a></li>
</ul>
```

**Comment by rhukster** [comment] 2016-03-11 17:27
Ah ok, must be the theme you are using then overriding the default pagination twig template.  

Which theme is it @morilval ???

**Comment by iconjenchua** [comment] 2016-03-14 15:56
had the same problem. did this to fix

`{% if pagination.hasPrev %}
                    {% set url =  (pagination.params ~ pagination.prevUrl)|replace({'//':'/'}) %}
                    {% set url = url == '' ? '/' : url %}
                    <li><a rel="prev" href="{{ url }}" class="label">Prev</a></li>
                {% else %}
                    <li><span>Prev</span></li>
              {% endif %}
`

**Comment by flaviocopes** [comment] 2016-03-14 16:03
Which theme are you using @iconjenchua? Cannot replicate the issue

**Comment by iconjenchua** [comment] 2016-03-14 16:07
It's actually a custom theme. But I simply just copied the `pagination.twig.html` from the pagination plugin folder @flaviocopes and removed the `base_url` variable.

**Comment by flaviocopes** [comment] 2016-03-14 16:28
The original twig presents the same problem?

**Comment by iconjenchua** [comment] 2016-03-14 16:37
@flaviocopes yes. But I see no problem when there are other taxonomy filters in the url (i.e. `categories:dog`), so that the url looks like this: `<url>/categories:dog/page:3`. In this case, the `prevUrl` and 1st page url will work as intended.

**Comment by gregorykelleher** [comment] 2016-03-21 13:59
I'd just like to chip in that I had noticed the same bug and came to the same conclusion as @iconjenchua. For me, I was using the Saturn theme but discovered the same issue when I installed lingonberry - prompting me to think that it was an over-ride issue with the default pagination twig template.

Like @iconjenchua I simply replaced the theme's pagination.html.twig inside partials with my modified  (same changes) pagination.html.twig from plugins and that did the trick.

**Comment by flaviocopes** [comment] 2016-03-21 15:53
Spot on @gregorykelleher.

- [ ] Saturn
- [ ] Lingonberry

Leaving this open, while fixing the issue in the themes. Add a comment if you see others using broken pagination overriddes.

**Comment by flaviocopes** [comment] 2016-03-21 16:36
@gregorykelleher no problem found with Lingonberry, are you sure?

**Comment by flaviocopes** [comment] 2016-03-29 16:11
Also appeared on Receptar https://github.com/getgrav/grav-theme-receptar/commit/aef868f886efc3bb748857d76702d40f099c1eb2

**Comment by iampox** [comment] 2016-03-29 16:20
There's also the same problem with the mediator theme (I just noticed it).  
Here's the content of the pagination.html.twig in my actual Mediator theme:
`<nav class="pagination" role="navigation">
    {% if pagination.hasNext %}
        <a class="older-posts" href="{{ base_url }}{{ pagination.params }}{{ pagination.nextUrl }}">&larr; Older posts</a>
    {% endif %}
    <span class="page-number">Page {{ uri.currentPage }} of {{ pagination|length }}</span>
    {% if pagination.hasPrev %}
        <a class="newer-posts" href="{{ base_url }}{{ pagination.params }}{{ pagination.prevUrl }}">Newer posts &rarr;</a>
    {% endif %}
</nav>`

**Comment by flaviocopes** [comment] 2016-03-29 16:46
@iampox thanks for reporting, fixed in https://github.com/getgrav/grav-theme-mediator/pull/8/files

**Comment by iampox** [comment] 2016-03-29 16:51
@flaviocopes Great, thank you very much!

**Comment by flaviocopes** [comment] 2016-03-30 13:25
Also fixed in other themes:

- [x] HPSTR
- [x] Lingonberry
- [x] Notepad
- [x] Pinpress
- [x] Sora Article
- [x] Twentyfifteen
- [x] Striped
- [x] Saturn

**Comment by TomasKoksch** [comment] 2016-05-01 22:06
Hi, I changed the file based on https://github.com/getgrav/grav-theme-receptar/commit/aef868f886efc3bb748857d76702d40f099c1eb2 but now there is only "page:1" instead of "siteadress:page1". Seems like there is need to change more thatn just one line in blog.html.twig

I have Receptar from Skeleton Install

**Comment by flaviocopes** [comment] 2016-05-02 09:13
What's your site URL, even if local? Subfolder or vhost?

**Comment by TomasKoksch** [comment] 2016-05-02 09:15
Hi its bylinkove-sneni.cz you can see it there. Now its without the fixed blog.html.twig and its not possible to go back from page 2 to page 1

**Comment by flaviocopes** [comment] 2016-06-07 21:03
We can close this as it's fixed for most themes

**Closed by flaviocopes** 2016-06-07 21:03 UTC
Labels: bug
